sudo: required
servicess:
  - docker
before_install:
  - docker build -t wee911/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wee911/react-test npm test -- --coverage

after_success:
  - docker build -t wee911/multi-client ./client
  - docker build -t wee911/multi-nginx ./nginx
  - docker build -t wee911/multi-server ./server
  - docker build -t wee911/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wee911/multi-client
  - docker push wee911/multi-nginx
  - docker push wee911/multi-server
  - docker push wee911/multi-worker
